mctpd: standalone-build: Fix phosphor-logging include path
Files in phosphor-logging were moved to different directory in:
e053884 ("build: Refactor to separate out library")

While the differences would normally be hidden with an install step,
we're not building/installing phosphor-logging so it causes an error:

mctpd/include/hw/aspeed/PCIeDriver.hpp:8:10: fatal error: phosphor-logging/log.hpp: No such file or directory
    8 | #include <phosphor-logging/log.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

Let's update standalone-build configuration to use new include path.

Tested: No code changes.

Change-Id: I70294a472bfecd8127389c0a572a0bf34642cfe7
Signed-off-by: Iwona Winiarska <iwona.winiarska@intel.com>