[mctpd] Fix unit test build error
Unit test build was failing with the error in nlohmann jsin. Fix the
same.

Error message was:
mctpd/buiild/libs/nlohmann-json/include/nlohmann/json.hpp:8110:42:   required from here
/usr/include/c++/10/bits/stl_uninitialized.h:137:72: error: ‘value’ is not a member of ‘std::is_constructible<nlohmann::basic_json<>, const nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&>’
  137 |       static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,
      |                                                                        ^~~~~
CMakeFiles/test-mctpd.dir/build.make:147: recipe for target 'CMakeFiles/test-mctpd.dir/src/utils/Configuration.cpp.o' failed

Tested:
Build passed

Change-Id: I863b0581129095af825010c6053c7972d838db48
Signed-off-by: Nidhin MS <nidhin.ms@intel.com>